import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";

const AppLayout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div>{children}</div>
      </main>
    </div>
  );
};

export default AppLayout;
